
services:
  - type: web
    name: telegram-chatgpt-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python sear.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_telegram_token_here
      - key: OPENAI_API_KEY
        value: your_openai_key_here
